import Banner from "@/components/home/Banner/Banner";
import { Metadata } from "next";
import "@/assets/css/globals.css"
import PageContainer from "@/components/layout/PageContainer";

export const metadata: Metadata = {
    title: "Calcular calorias | Digital Nutri",
    description: "Generated by create next app",
};

export default function PageComponent() {
    return (
        <PageContainer>
            <Banner />
        </PageContainer>

    );
}
