import { Metadata } from "next";
import "@/assets/css/globals.css"
 
import Banner from "@/components/layout/home/Banner/Banner";
import PageContainer from "@/components/default/PageContainer/PageContainer";

export const metadata: Metadata = {
    title: "Calcular calorias | Digital Nutri",
    description: "Generated by create next app",
};

export default function PageComponent() {
    return (
        <PageContainer>
            <Banner />
        </PageContainer>
    );
}
