import { Metadata } from "next";
import "@/assets/css/globals.css"
import PageContainer from "@/components/layout/PageContainer";
import Banner from "@/components/layout/home/Banner/Banner";

export const metadata: Metadata = {
    title: "Calcular calorias | Digital Nutri",
    description: "Generated by create next app",
};

export default function PageComponent() {
    return (
        <PageContainer>
            <Banner />
        </PageContainer>

    );
}
